### ISSUE TITLE
在群辉下用docker方式运行，使用的映像是mritd/tpclash，启动后报错

### ISSUE THREAD

**Issue by deepdream** [TPClash/tpclash#12]
错误信息：
FATL [main] failed to start clash process: fork/exec /data/clash/xclash: invalid argument: [/data/clash/xclash -f /data/clash/xclash.yaml -d /data/clash -ext-ui /data/clash/yacd]
我的clash.yaml文件放在/root/config.yaml，如下，为排查问题，未加入任何proxys信息和rules
tun:
  enable: true
  stack: system
  dns-hijack:
    - any:53

  auto-route: true
  auto-redir: true
  auto-detect-interface: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29

**Comment by j33h22** [comment]
Dear [deepdream](https://github.com/deepdream)

  I am sorry for that.
 Because of the original author has deleted the docker image code of TPClash,We can't make the Docker service can usable again.
 Maybe we will use the other way to make our TPClash can run Docker again.

Best regrads,
Ju33Huang22
